{% set name = "googleapis-cpp" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/cpp-cmakefiles/archive/v{{ version }}.tar.gz
  sha256: 43d5d187722f23e84a320529c04070285f4905b2011396451e61720bd35d047e

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("googleapis-cpp", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - c-ares
    - grpc-cpp
    - libprotobuf
  run:

test:
  commands:
    - test -f $PREFIX/lib/cmake/googleapis/googleapis-targets.cmake  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_bigtable_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_pubsub_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_spanner_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_storage_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_longrunning_operations_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_api_http_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_api_annotations_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_api_auth_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_api_client_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_api_field_behavior_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_api_resource_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_devtools_cloudtrace_v2_trace_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_rpc_status_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/libgoogleapis_cpp_type_expr_protos${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/google/pubsub/v1/pubsub.pb.h  # [unix]
    - test -f $PREFIX/include/google/pubsub/v1/pubsub.grpc.pb.h  # [unix]
    - test -f $PREFIX/include/google/pubsub/v1/pubsub.proto  # [unix]

about:
  home: https://github.com/googleapis/cpp-cmakefiles
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Create C++ libraries from the googleapis protos.

extra:
  recipe-maintainers:
    - xhochy
